# Generated by Django 4.0.3 on 2022-03-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('teamname', models.CharField(max_length=255)),
                ('teamlogo', models.ImageField(default='a.png', upload_to='images/')),
                ('player1name', models.CharField(max_length=255)),
                ('player1image', models.ImageField(default='a.png', upload_to='images/')),
                ('player2name', models.CharField(max_length=255)),
                ('player2image', models.ImageField(default='a.png', upload_to='images/')),
                ('player3name', models.CharField(max_length=255)),
                ('player3image', models.ImageField(default='a.png', upload_to='images/')),
                ('player4name', models.CharField(max_length=255)),
                ('player4image', models.ImageField(default='a.png', upload_to='images/')),
                ('player5name', models.CharField(max_length=255, null=True)),
                ('player5image', models.ImageField(default='a.png', null=True, upload_to='images/')),
                ('player6name', models.CharField(max_length=255, null=True)),
                ('player6image', models.ImageField(default='a.png', null=True, upload_to='images/')),
            ],
        ),
    ]
