# Generated by Django 4.0.3 on 2022-03-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='player5image',
            field=models.ImageField(blank=True, default='a.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='player5name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='emp',
            name='player6image',
            field=models.ImageField(blank=True, default='a.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='emp',
            name='player6name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
